// <auto-generated />
namespace TheaterGuide.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class add_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_field));
        
        string IMigrationMetadata.Id
        {
            get { return "201311112246239_add_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
