// <auto-generated />
namespace TheaterGuide.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class change_field_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_field_name));
        
        string IMigrationMetadata.Id
        {
            get { return "201311110056396_change_field_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
